version: "3.7"

services:
  webgen-keycloak:
    image: jboss/keycloak
    container_name: webgen-auth
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080

  webgen-db:
    image: amazon/dynamodb-local:latest
    container_name: webgen-db
    restart: unless-stopped
    volumes:
      - ./docker/data/webgen-db:/data/db

  sherweb-server:
    build:
      context: ./server
    container_name: sherweb-server
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/

    env_file:
      - ./server/.env
    ports:
      - 4050:4050
    depends_on:
      - webgen-db
    environment:
      WAIT_HOSTS: webgen-db:8000
