version: "3.5"

services:
  # taxgen_db:
  #   image: mongo:latest
  #   container_name: taxgen_db
  #   restart: unless-stopped
  #   volumes:
  #     - ./docker/data/taxgen_db:/data/db

  sherweb_server:
    build:
      context: ./server
    container_name: sherweb_server
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/

    env_file:
      - ./server/.env
    ports:
      - 4050:4050
    # depends_on:
    #   - taxgen_db
    # environment:
    #   WAIT_HOSTS: taxgen_db:27017
