version: "3.5"

services:
  webgen_db:
    image: amazon/dynamodb-local:latest
    container_name: webgen_db
    restart: unless-stopped
    volumes:
      - ./docker/data/webgen_db:/data/db

  sherweb_server:
    build:
      context: ./server
    container_name: sherweb_server
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/

    env_file:
      - ./server/.env
    ports:
      - 4050:4050
    depends_on:
      - webgen_db
    environment:
      WAIT_HOSTS: webgen_db:8000
